# Generated by Django 2.1.3 on 2019-01-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='privacy',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Secret')], default=0, verbose_name='privacy'),
        ),
    ]
