# Generated by Django 2.1.3 on 2019-01-13 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
