# Generated by Django 2.1.3 on 2019-01-03 11:09

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('user_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Premium')], default=0, null=True, verbose_name='user_type')),
                ('contact', models.CharField(blank=True, max_length=14, null=True, verbose_name='contact')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=2, null=True, verbose_name='gender')),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.utils.upload_image_path, verbose_name='image')),
                ('about', models.TextField(blank=True, max_length=150, null=True, verbose_name='about')),
                ('address', models.CharField(blank=True, max_length=77, null=True, verbose_name='address')),
                ('facebook', models.CharField(blank=True, max_length=300, null=True, verbose_name='facebook')),
                ('linkedin', models.CharField(blank=True, max_length=300, null=True, verbose_name='linkedin')),
                ('website', models.CharField(blank=True, max_length=300, null=True, verbose_name='website')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
