# Generated by Django 2.1.3 on 2019-01-05 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_membertrack_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membertrack',
            name='total',
        ),
    ]
