# Generated by Django 2.1.3 on 2019-01-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_trackerfield_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerfield',
            name='cost',
        ),
    ]
