# Generated by Django 2.1.3 on 2019-01-05 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_totalholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalholder',
            options={'ordering': ['-member__room__created_at'], 'verbose_name': 'Total Holder', 'verbose_name_plural': 'Total Holders'},
        ),
        migrations.AddField(
            model_name='totalholder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalholder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
