# Generated by Django 2.1.3 on 2019-01-06 03:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_totalholder_cash_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_next_day',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='meal next day'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_today',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='meal today'),
        ),
    ]
