# Generated by Django 2.1.3 on 2019-01-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20190106_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['member__created_at'], 'verbose_name': 'Meal Entry', 'verbose_name_plural': 'Meal Entries'},
        ),
    ]
