# Generated by Django 2.1.3 on 2019-01-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_shopping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopping',
            options={'ordering': ['-member__room__created_at'], 'verbose_name': 'Shopping', 'verbose_name_plural': 'Shoppings'},
        ),
    ]
