# Generated by Django 2.1.3 on 2019-01-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20190108_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='quantity unit'),
        ),
    ]
