# Generated by Django 2.1.3 on 2019-01-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_shoppingtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingtype',
            options={'ordering': ['-room__created_at'], 'verbose_name': 'Shopping Type', 'verbose_name_plural': 'Shopping Types'},
        ),
    ]
