# Generated by Django 2.1.3 on 2019-01-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20190108_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingtype',
            name='privacy',
        ),
        migrations.AddField(
            model_name='shoppingtype',
            name='shopping_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'INDIVIDUAL MEMBER DEPENDENT SHOPPING'), (1, 'ROOM MANAGER DEPENDENT SHOPPING')], default=0, verbose_name='shopping type'),
        ),
    ]
