# Generated by Django 2.1.3 on 2019-01-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20190108_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_shopping', to='rooms.Room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='shoppingtype',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_shopping_type', to='rooms.Room', verbose_name='room'),
        ),
    ]
