# Generated by Django 2.1.3 on 2019-01-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20190108_0312'),
        ('tracker', '0023_auto_20190108_0526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalholder',
            options={'ordering': ['-room__created_at'], 'verbose_name': 'Total Holder', 'verbose_name_plural': 'Total Holders'},
        ),
        migrations.AddField(
            model_name='totalholder',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_total_holder', to='rooms.Room', verbose_name='room'),
        ),
    ]
