# Generated by Django 2.1.3 on 2019-01-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20190108_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalholder',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_total_holder', to='rooms.Room', verbose_name='room'),
        ),
    ]
