# Generated by Django 2.1.3 on 2019-01-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_auto_20190108_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalholder',
            name='meal_total',
        ),
    ]
