# Generated by Django 2.1.3 on 2019-01-10 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_auto_20190110_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalholder',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_total_holder', to='memberships.Membership', verbose_name='member'),
        ),
    ]
