# Generated by Django 2.1.3 on 2019-01-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20190110_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalholder',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
