# Generated by Django 2.1.3 on 2019-01-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_shopping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
