# Generated by Django 2.1.3 on 2019-01-11 02:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_auto_20190111_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cost'),
        ),
    ]
