# Generated by Django 2.1.3 on 2019-01-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_auto_20190111_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slugs'),
        ),
    ]
