# Generated by Django 2.1.3 on 2019-01-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_shopping_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
