# Generated by Django 2.1.3 on 2019-01-12 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_auto_20190111_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='shopping_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_type', to='tracker.ShoppingType', verbose_name='shopping type'),
        ),
    ]
