# Generated by Django 2.1.3 on 2019-01-12 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_shopping_shopping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='shopping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_type', to='tracker.ShoppingType', verbose_name='shopping type'),
        ),
    ]
