# Generated by Django 2.1.3 on 2019-01-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_auto_20190112_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='shopping_type',
        ),
        migrations.AddField(
            model_name='shopping',
            name='shop_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'INDIVIDUAL'), (1, 'MANAGERIAL')], default=0, verbose_name='shop type'),
        ),
    ]
