# Generated by Django 2.1.3 on 2019-01-12 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('tracker', '0039_auto_20190112_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='member',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='room',
        ),
        migrations.AddField(
            model_name='shopping',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_shopping', to='memberships.Membership', verbose_name='created by'),
        ),
    ]
