# Generated by Django 2.1.3 on 2019-01-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_auto_20190112_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopping',
            options={'ordering': ['-room__created_at'], 'verbose_name': 'Shopping', 'verbose_name_plural': 'Shoppingss'},
        ),
    ]
