# Generated by Django 2.1.3 on 2019-01-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0044_auto_20190113_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalholder',
            name='date',
        ),
    ]
