# Generated by Django 2.1.3 on 2019-01-24 00:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0045_remove_totalholder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalholder',
            name='cash_deposit',
        ),
        migrations.AddField(
            model_name='totalholder',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='deposit amount'),
        ),
        migrations.AddField(
            model_name='totalholder',
            name='deposit_title',
            field=models.CharField(max_length=20, null=True, verbose_name='deposit title'),
        ),
    ]
