# Generated by Django 2.1.3 on 2019-01-24 02:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('rooms', '0006_auto_20190113_0315'),
        ('tracker', '0047_auto_20190124_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDepositField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=60, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_field_room', to='rooms.Room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Cash Deposit Field',
                'verbose_name_plural': 'Cash Deposit Fields',
                'ordering': ['-room__created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDepositMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deposit_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_deposit_field', to='tracker.CashDepositField', verbose_name='deposit field')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_cash_deposit', to='memberships.Membership', verbose_name='member')),
            ],
            options={
                'verbose_name': 'Member Cash Deposit',
                'verbose_name_plural': 'Member Cash Deposits',
                'ordering': ['-member__room__created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='cashdeposit',
            name='member',
        ),
        migrations.DeleteModel(
            name='CashDeposit',
        ),
    ]
